Specify explicit `min-release-age` for `npm install`
Prevents the following error on `npm install`:

```
npm error code ETARGET
npm error notarget No matching version found for @csstools/css-syntax-patches-for-csstree@^1.1.8 with a date before 8/13/2026, 2:51:35 AM.
npm error notarget In most cases you or one of your dependencies are requesting a package version that doesn't exist.
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2026-08-20T02_51_35_250Z-debug-0.log
Error: 'npm install --ignore-scripts --no-audit --no-save --allow-git=all github:stylelint/stylelint' failed. Visit https://github.com/stylelint-scss/stylelint-scss
Error: Process completed with exit code 1.
```

Ref: https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/32326072552/job/96297569415#step:10:13

Cause: `stylelint-scss` sets `min-release-age=7`, which fails `npm install github:stylelint/stylelint`.
Ref: https://github.com/stylelint-scss/stylelint-scss/blob/0b490637d921e46c96d2bb2847498a0b083e1547/.npmrc#L2