Fix pnpm installation
Resolves the recent error when installing pnpm:

```text
SyntaxError: Invalid or unexpected token
```

-- <https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/33940983085/job/101238310430#step:7:23>

Here is the error cause.

`pnpm@12.0` was out on 2026-08-26, last month.
Ref: https://pnpm.io/blog/releases/12.0

With this version, the way to install pnpm has changed.
`npx get-pnpm` is now needed instead of `npm i`.
Ref: https://github.com/pnpm/get.pnpm.io/tree/main/get-pnpm